name = "Playing With Fire"
author = "dozingpip"
version = "0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b42a059bc2965ec27f50d4df607ad97887844f6c97220f322d9a805e8985b60"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
